const nodemailer = require("nodemailer");

const ADMIN_EMAIL = process.env.ADMIN_EMAIL || "rathodshubham7711@gmail.com";

// Create reusable transporter
const createTransporter = () => {
  if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
    return nodemailer.createTransport({
      service: process.env.EMAIL_SERVICE || "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });
  }

  // Fallback if custom SMTP host is provided
  if (process.env.SMTP_HOST && process.env.SMTP_PORT) {
    return nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT),
      secure: process.env.SMTP_SECURE === "true",
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }

  return null;
};

/**
 * Send contact inquiry email to the admin
 * @param {Object} data - { name, email, message, subject }
 * @returns {Promise<boolean>}
 */
const sendContactEmail = async ({ name, email, message, subject }) => {
  const emailSubject = subject || `New Contact Message on Woofy from ${name}`;
  const transporter = createTransporter();

  const htmlContent = `
    <div style="font-family: 'Inter', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
      <div style="background-color: #0f172a; padding: 24px; text-align: center;">
        <h1 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: -0.02em;">Woofy.</h1>
        <p style="color: #94a3b8; margin: 6px 0 0 0; font-size: 14px;">New Contact Us Notification</p>
      </div>
      <div style="padding: 30px 24px; color: #1e293b; line-height: 1.6;">
        <h2 style="font-size: 18px; margin-top: 0; color: #0f172a; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">
          Message Details
        </h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 15px;">
          <tr>
            <td style="padding: 8px 0; color: #64748b; width: 120px; font-weight: 600;">Sender Name:</td>
            <td style="padding: 8px 0; color: #0f172a; font-weight: bold;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #64748b; font-weight: 600;">Sender Email:</td>
            <td style="padding: 8px 0;"><a href="mailto:${email}" style="color: #2563eb; text-decoration: none;">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 8px 0; color: #64748b; font-weight: 600;">Received Date:</td>
            <td style="padding: 8px 0; color: #334155;">${new Date().toLocaleString("en-US", { timeZone: "Asia/Kolkata" })} (IST)</td>
          </tr>
        </table>

        <div style="background-color: #f8fafc; border-left: 4px solid #2563eb; padding: 16px; border-radius: 4px; margin-top: 15px;">
          <strong style="display: block; color: #0f172a; margin-bottom: 6px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em;">Message:</strong>
          <p style="margin: 0; white-space: pre-wrap; color: #334155; font-size: 15px;">${message}</p>
        </div>

        <div style="margin-top: 30px; text-align: center;">
          <a href="mailto:${email}?subject=Re: ${encodeURIComponent(emailSubject)}" style="display: inline-block; background-color: #0f172a; color: #ffffff; text-decoration: none; padding: 12px 24px; border-radius: 4px; font-weight: 600; font-size: 14px;">
            Reply to ${name}
          </a>
        </div>
      </div>
      <div style="background-color: #f8fafc; padding: 16px; text-align: center; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8;">
        This notification was automatically generated by Woofy Pet Care Management platform.
      </div>
    </div>
  `;

  if (!transporter) {
    console.log("--------------------------------------------------");
    console.log("ℹ️ [EMAIL NOTIFICATION SIMULATION]");
    console.log(`To: ${ADMIN_EMAIL}`);
    console.log(`From: ${name} <${email}>`);
    console.log(`Subject: ${emailSubject}`);
    console.log(`Message: ${message}`);
    console.log("Tip: Add EMAIL_USER and EMAIL_PASS to your .env to send real emails via Gmail SMTP.");
    console.log("--------------------------------------------------");
    return true; // Gracefully simulate success in local development
  }

  try {
    const info = await transporter.sendMail({
      from: `"${name} (via Woofy)" <${process.env.EMAIL_USER || email}>`,
      replyTo: email,
      to: ADMIN_EMAIL,
      subject: emailSubject,
      text: `Name: ${name}\nEmail: ${email}\n\nMessage:\n${message}`,
      html: htmlContent,
    });
    console.log("[Mailer] Contact email sent successfully:", info.messageId);
    return true;
  } catch (error) {
    console.error("[Mailer] Failed to send contact email via SMTP:", error.message);
    return false;
  }
};

module.exports = {
  sendContactEmail,
  ADMIN_EMAIL,
};
