const mongoose = require("mongoose");

const vaccinationSchema = new mongoose.Schema(
  {
    pet: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Pet",
      required: true,
      index: true,
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    vaccineName: {
      type: String,
      required: true,
      trim: true,
    },
    category: {
      type: String,
      enum: ["Core Vaccine", "Deworming", "Booster", "Non-Core", "Custom"],
      default: "Core Vaccine",
      index: true,
    },
    targetAgeWeeks: {
      type: Number,
      default: null,
    },
    targetStageDescription: {
      type: String,
      default: "",
    },
    dueDate: {
      type: Date,
      required: true,
      index: true,
    },
    administeredDate: {
      type: Date,
      default: null,
    },
    status: {
      type: String,
      enum: ["Upcoming", "Due Soon", "Overdue", "Completed", "Skipped"],
      default: "Upcoming",
      index: true,
    },
    clinicOrVetName: {
      type: String,
      trim: true,
      default: "",
    },
    batchNumber: {
      type: String,
      trim: true,
      default: "",
    },
    certificateImage: {
      type: String,
      default: "",
    },
    notes: {
      type: String,
      trim: true,
      default: "",
    },
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
    reminderSent: {
      type: Boolean,
      default: false,
    },
    lastReminderDate: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  },
);

vaccinationSchema.index({ pet: 1, dueDate: 1 });
vaccinationSchema.index({ user: 1, status: 1 });

const Vaccination = mongoose.model("Vaccination", vaccinationSchema);

module.exports = Vaccination;
